### ISSUE TITLE
What's wrong with this plugin

### ISSUE THREAD

**Issue by DarNull** [Runian/helix-plugins#3]
[ULib] lua/ulib/shared/sh_ucl.lua:48: attempt to index local 'ply' (a nil value)
  1. query - lua/ulib/shared/sh_ucl.lua:48
   2. fn - lua/ulib/shared/cami_ulib.lua:18
    3. Call - lua/ulib/shared/hook.lua:109
     4. PlayerHasAccess - gamemodes/helix/gamemode/core/libs/thirdparty/sh_cami.lua:383
      5. DoClick - gamemodes/animstalker_rp/plugins/spawnmenu_itemtab.lua:130
       6. unknown - lua/vgui/dlabel.lua:237

wut

**Comment by Runian** [comment]
Should be solved by #2
